# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab53530a77592a6d1f0af5ddb084bd9058073eef56d2d96d4f980e405934499f7825bd184bb18ea250a0c4066204ed7b0eb5a9f6323c0dccfc5f26928710746f

test:
  secret_key_base: 65e906321daadc88de415d44baf2c26ea961890a1edebb614e7613ba3f03cf1450ecf7fa5f8de172536a4310b007d697eb734d55a034264b6309925b9e6cae9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
